carts/urls.py
from django.conf.urls import url
from .views import cart_home,cart_update,checkout_home,checkout_done_view,cart_api_view

urlpatterns = [
    url(r'^$',cart_home,name='home'),
    url(r'^update/$',cart_update,name='update'),
    url(r'^checkout/$',checkout_home,name='checkout'),
    url(r'^success/$',checkout_done_view,name='success'),
    url(r'^api/$',cart_api_view,name='api'),
]

orders/urls.py
from django.conf.urls import url
from .views import OrderListView,OrderDetailView

urlpatterns = [
    url(r'^$',OrderListView.as_view(),name='list'),
    url(r'^(?P<order_id>[0-9a-zA-Z]+)/$',OrderDetailView.as_view(),name='detail'),
]

src/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from .views import guest_register_page,RegisterView,LoginView

urlpatterns = [
    url(r'^login/$',LoginView.as_view(),name='login'),
    url(r'^logout/$',LogoutView.as_view(),name='logout'),
    url(r'^register/$',RegisterView.as_view(),name='register'),
    url(r'^guest/$',guest_register_page,name='guest'),

]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf.urls import url,include
from django.contrib import admin


from .views import home_page,about_page,contact_page
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^about/$', about_page,name='about'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='address_reuse'),
    url(r'^$', home_page,name='home'),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^search/',include('search.urls',namespace='search')),
    url(r'^carts/',include('carts.urls',namespace='carts')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^billing/',include('billing.urls',namespace='billing')),
    url(r'^marketing/',include('marketing.urls',namespace='marketing')),
]
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
		AbstractBaseUser,BaseUserManager
	)

class UserManager(BaseUserManager):
	def create_user(self,email,full_name=None,password=None,is_active=True,is_staff=False,is_admin=False):
		if not email:
			raise ValueError('Users must have an email address.')
		if not password:
			raise ValueError('Users must have a password.')
		user_obj = self.model(
			email=self.normalize_email(email)
			)
		user_obj.set_password(password)
		user_obj.staff=is_staff
		user_obj.admin=is_admin
		user_obj.active=is_active
		user_obj.full_name=full_name
		user_obj.save(using=self._db)
		return user_obj
	def create_stuff(self,email,full_name=None,password=None):
		user=self.create_user(
			email,
			full_name=full_name,
			password=password,
			is_staff=True,
			)
		return user
	def create_superuser(self,email,full_name=None,password=None):
		user=self.create_user(
			email,
			full_name=full_name,
			password=password,
			is_staff=True,
			is_admin=True,
			)
		return user

class User(AbstractBaseUser):
	email = models.EmailField(unique=True,max_length=255)
	full_name=models.CharField(max_length=255,blank=True,null=True)
	active = models.BooleanField(default=True)
	staff = models.BooleanField(default=False)
	admin = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)

	objects = UserManager()
	USERNAME_FIELD='email'

	REQUIRED_FIELDS=[]

	def __str__(self):
		return self.email
	def get_full_name(self):
		if self.full_name:
			return self.full_name
		return self.email
	def get_short_name(self):
		return self.email
	def has_perm(self,perm,obj=None):
		return True
	def has_module_perms(self,app_label):
		return True
	
	@property
	def is_staff(self):
		return self.staff
	@property
	def is_admin(self):
		return self.admin
	@property
	def is_active(self):
		return self.active



# Create your models here.
class GuestEmail(models.Model):
	email = models.EmailField()
	active = models.BooleanField(default=True)
	update = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.email

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User=get_user_model()



class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name') #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'full_name','active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]



class GuestForm(forms.Form):
	email = forms.EmailField()

class LoginForm(forms.Form):
	email=forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
	password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}))

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email','full_name') #'full_name',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        #user.active=False
        if commit:
            user.save()
        return user

src/accounts/views.py
from django.contrib.auth import authenticate,login,get_user_model
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from django.views.generic import CreateView,FormView

from .forms import LoginForm,RegisterForm,GuestForm
from .models import GuestEmail
from .signals import user_logged_in_signal
def guest_register_page(request):
	form=GuestForm(request.POST or None)
	context={
		'form':form,
	}
	next_=request.GET.get('next')
	next_post=request.POST.get('next')
	redirect_path=next_ or next_post or None
	if form.is_valid():
		email=form.cleaned_data.get('email')
		new_guest_email=GuestEmail.objects.create(email=email)
		request.session['guest_email_id']=new_guest_email.id
		if is_safe_url(redirect_path,request.get_host()):
			return redirect(redirect_path)
		else:
			return redirect('accounts:register')
	return redirect('accounts:register')
class LoginView(FormView):
	form_class=LoginForm
	template_name='accounts/login.html'
	def form_valid(self,form):
		request=self.request
		next_=request.GET.get('next')
		next_post=request.POST.get('next')
		redirect_path=next_ or next_post or None

		cd=form.cleaned_data
		email=cd['email']
		password=cd['password']
		user=authenticate(request,email=email,password=password)
		if user is not None:
			login(request,user)
			user_logged_in_signal.send(user.__class__,instance=user,request=request)
			try:
				del request.session['guest_email_id']
			except:
				pass
			if is_safe_url(redirect_path,request.get_host()):
				return redirect(redirect_path)
			else:
				return redirect('/')
		return super(LoginView,self).form_invalid(form)

User=get_user_model()
class RegisterView(CreateView):
	form_class=RegisterForm
	template_name='accounts/register.html'
	success_url="accounts:login"

src/templates/base/nav.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:register' as register_url %}
{% url 'carts:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class='container'>
  <a class="navbar-brand" href="{{ home_url }}">
    <img src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
  {% if brand_name %}{{ brand_name }}{% else %}eCommerce{% endif %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{ contact_url }}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
        <a class="nav-link" href="{{ products_list_url }}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">Logout</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">Login</a>
      </li>
       <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Register</a>
      </li>            
      {% endif %}
       <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="nav-link" href="{{ cart_url }}"><span class='navbar-cart-count'>{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
      </li>       
    </ul>
    {% include 'search/snippets/search.html' %}
  </div>
</div>
</nav>