carts/urls.py
from django.conf.urls import url
from .views import cart_home,cart_update,checkout_home,checkout_done_view,cart_api_view

urlpatterns = [
    url(r'^$',cart_home,name='home'),
    url(r'^update/$',cart_update,name='update'),
    url(r'^checkout/$',checkout_home,name='checkout'),
    url(r'^success/$',checkout_done_view,name='success'),
    url(r'^api/$',cart_api_view,name='api'),
]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf.urls import url,include
from django.contrib import admin


from .views import home_page,about_page,contact_page
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^about/$', about_page,name='about'),
    url(r'^checkout/address/create/$',checkout_address_create_view,name='address_create'),
    url(r'^checkout/address/reuse/$',checkout_address_reuse_view,name='address_reuse'),
    url(r'^$', home_page,name='home'),
    url(r'^products/',include('products.urls',namespace='products')),
    url(r'^search/',include('search.urls',namespace='search')),
    url(r'^carts/',include('carts.urls',namespace='carts')),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^billing/',include('billing.urls',namespace='billing')),
    url(r'^marketing/',include('marketing.urls',namespace='marketing')),
]
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save,post_save,m2m_changed

from products.models import Product

User = settings.AUTH_USER_MODEL

# Create your models here.
class CartManager(models.Manager):
	def new_or_get(self,request):
		cart_id=request.session.get('cart_id',None)
		qs=self.get_queryset().filter(id=cart_id)
		if qs.count() == 1:
			new_obj=False
			cart_obj=qs.first()
			if request.user.is_authenticated() and cart_obj.user is None:
				cart_obj.user=request.user
				cart_obj.save()
		else:
			cart_obj=Cart.objects.new_cart(request.user)
			new_obj=True
			request.session['cart_id']=cart_obj.id
		return cart_obj,new_obj
	def new_cart(self,user=None):
		user_obj=None
		if user is not None:
			if user.is_authenticated():
				user_obj=user
		return self.model.objects.create(user=user_obj)
class Cart(models.Model):
	user       =models.ForeignKey(User,null=True,blank=True)
	products   =models.ManyToManyField(Product,blank=True)
	subtotal      =models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
	total      =models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
	updated    =models.DateTimeField(auto_now=True)
	timestamp  =models.DateTimeField(auto_now_add=True)
	objects    =CartManager()

	def __str__(self):
		return  str(self.id)


def m2m_changed_save_receiver(sender,instance,action,*args,**kwargs):
	if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
		products=instance.products.all()
		total = 0
		for x in products:
			total+=x.price
			instance.subtotal=total
		if instance.subtotal != instance.total:
			instance.save()
m2m_changed.connect(m2m_changed_save_receiver,sender=Cart.products.through)

def pre_save_receiver(sender,instance,*args,**kwargs):
	if instance.subtotal > 0:
		instance.total = float(instance.subtotal)*float(1.08)
	else:
		instance.total = 0.00

pre_save.connect(pre_save_receiver,sender=Cart)

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from accounts.models import GuestEmail
from django.conf import settings
from addresses.forms import AddressCheckoutForm
from addresses.models import Address
from accounts.forms import LoginForm,GuestForm
from products.models import Product
from .models import Cart
from orders.models import Order
from billing.models import BillingProfile

import stripe
STRIPE_SECRET_KEY=getattr(settings,'STRIPE_SECRET_KEY','sk_test_ZP7A7uDCNapWFDAj0MFwejdR')
STRIPE_PUB_KEY=getattr(settings,'STRIPE_PUB_KEY','pk_test_OHADWNQQHJbzdqNAMtlMYOjo')
stripe.api_key=STRIPE_SECRET_KEY
# Create your views here.
def cart_api_view(request):
	cart_obj,new_obj=Cart.objects.new_or_get(request)
	json_data={
		'products':[{'name':x.title,'price':x.price,'url':x.get_absolute_url(),'id':x.id} for x in cart_obj.products.all()],
		'subtotal':cart_obj.subtotal,
		'total':cart_obj.total,
	}
	return JsonResponse(json_data)
def cart_home(request):
	cart_obj,new_obj=Cart.objects.new_or_get(request)
	return render(request,'carts/home.html',{'cart':cart_obj})

def cart_update(request):
	product_id=request.POST.get('product_id')
	if product_id is not None:
		try:
			obj=Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print('Show message to the user')
			redirect("carts:home")
		cart_obj,new_obj=Cart.objects.new_or_get(request)
		if obj in cart_obj.products.all():
			cart_obj.products.remove(obj)
			added=False
		else:
			cart_obj.products.add(obj)
			added=True
	request.session['cart_items']=cart_obj.products.count()
	if request.is_ajax():
		print('Ajax Request')
		json_data={
			'added':added,
			'removed': not added,
			'cartItemsCount':cart_obj.products.count(),
		}
		return JsonResponse(json_data)
	return redirect("carts:home")

def checkout_home(request):
	cart_obj,new_cart_obj=Cart.objects.new_or_get(request)
	order_obj=None
	if new_cart_obj or cart_obj.products.count() == 0:
		return redirect("carts:home")

	login_form=LoginForm(request=request)
	guest_form=GuestForm(request=request)
	address_form=AddressForm()
	shipping_address_id=request.session.get('shipping_address_id',None)
	billing_address_id=request.session.get('billing_address_id',None)

	billing_profile,billing_profile_created=BillingProfile.objects.new_or_get(request)
	address_qs=None
	has_card=False
	if billing_profile is not None:
		if request.user.is_authenticated():
			address_qs=Address.objects.filter(billing_profile=billing_profile)
		order_obj,order_obj_created=Order.objects.new_or_get(billing_profile,cart_obj)	
		if shipping_address_id:
			shipping_address=Address.objects.get(id=shipping_address_id)
			order_obj.shipping_address=shipping_address
			del request.session['shipping_address_id']
		if billing_address_id:
			billing_address=Address.objects.get(id=billing_address_id)
			order_obj.billing_address=billing_address
			del request.session['billing_address_id']
		if shipping_address_id or billing_address_id:
			order_obj.save()
		has_card=billing_profile.has_card
	if request.method == 'POST':
		is_prepared=order_obj.check_done()
		if is_prepared:
			is_paid,charge_msg=billing_profile.charge(order_obj)
			if is_paid:
				order_obj.mark_paid()
				request.session['cart_items']=0
				del request.session['cart_id']
				if not billing_profile.user:
					billing_profile.set_cards_inactive()
			else:
				print(charge_msg)
				return redirect("carts:checkout")
		return redirect('carts:success')
	context={
		'object':order_obj,
		'billing_profile':billing_profile,
		'login_form':login_form,
		'guest_form':guest_form,
		'address_form':address_form,
		'address_qs':address_qs,
		'has_card':has_card,
		'publish_key':STRIPE_PUB_KEY,
	}
	return render(request,'carts/checkout.html',context)


def checkout_done_view(request):
	context={}
	return render(request,'carts/checkout_done.html',context)

templates/carts/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Cart | {{ block.super }}{% endblock head_title%}
{% block content %}

{% if not billing_profile %}
	<div class='row text-center'>
		<div class='col-12 col-md-6'>
			<h2>Login</h2>
			{% include 'accounts/snippets/form.html' with form=login_form next=request.build_absolute_uri %}
		</div>
		<div class='col-12 col-md-6'>
			<h2>Continue as a guest</h2>
			{% url 'guest' as guest_url %}
			{% include 'accounts/snippets/form.html' with form=guest_form next=request.build_absolute_uri action_url=guest_url %}
		</div>
	</div>

{% else %}
	{% if not object.shipping_address %}
	<div class='row'>
		<div class='col-12'> 
		<p class='lead'>Shipping Address</p>
		<hr/>
	</div>
	</div>
		<div class='row'>
			<div class='col-6'>
			{% url 'address_create' as address_create_url %}
			{% include 'addresses/snippets/form.html' with form=address_form next=request.build_absolute_uri action_url=address_create_url address_type='shipping' %}
		</div>
		<div class='col-6'>
			{% url 'address_reuse' as address_reuse_url %}
			{% include 'addresses/snippets/pre_address.html' with address_qs=address_qs next=request.build_absolute_uri address_type='shipping' action_url=address_reuse_url %}
		</div>
		</div>

	{% elif not object.billing_address %}
	<div class='row'>
		<div class='col-12'> 
			<p class='lead'>Billing Address</p>
			<hr/>
		</div>
	</div>
	<div class='row'>
		<div class='col-6'>
			{% url 'address_create' as address_create_url %}
			{% include 'addresses/snippets/form.html' with form=address_form next=request.build_absolute_uri action_url=address_create_url address_type='billing' %}	
		</div>
		<div class='col-6'>
			{% url 'address_reuse' as address_reuse_url %}
			{% include 'addresses/snippets/pre_address.html' with address_qs=address_qs next=request.build_absolute_uri address_type='billing' action_url=address_reuse_url %}
		</div>
	</div>
	{% else %}
		{% if not has_card %}
		<div class='stripe-paymment-form' data-token="{{ publish_key }}" data-next-url="{{ request.build_absolute_uri }}" ></div>
		{% else %}
		<p class='leader'>Checkout</p>
		<hr/>
		<p>Cart Items       : {% for product in object.cart.products.all %}{{ product.title }}{% endfor %}</p>
		<p>Shipping Address : {{ object.shipping_address_final }}</p>
		<p>Billing Address  : {{ object.billing_address_final }}</p>
		<p>Payment Method   : {{ billing_profile.default_card }}<a href="{{ billing_profile.get_payment_method_url }}?next={{ request.build_absolute_uri }}">[Change?]</a></p>
		<p>Cart Total       : {{ object.cart.total }}</p>
		<p>Shipping Total   : {{ object.shipping_total }}</p>
		<p>Order Total      : {{ object.total }}</p>

		<form class='form' method='POST' action="">{% csrf_token %}
			<button class='btn btn-success' type='submit'>Checkout</button>
		</form>
		{% endif %}
	{% endif %}
{% endif %}

{% endblock content %}

templates/carts/checkout_done.html
{% extends 'base.html' %}

{% block head_title %}Checkout Success | {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='row'>
	<div class='col-6 mx-auto py-5'>
		<h1 class='display-1'>Thank you for your order.</h1>
	</div>
</div>
{% endblock content %}

templates/carts/home.html
{% extends 'base.html' %}
{% load static %}
{% block head_title %}Cart | {{ block.super }}{% endblock head_title%}
{% block content %}
{% if cart.products.exists %}
<table class="table cart-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product Name</th>
      <th scope="col">Prouct Price</th>
    </tr>
  </thead>
  <tbody class='cart-body'>
  	{% for product in cart.products.all %}
    <tr class='cart-products'>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>  
      {% include 'carts/remove_form.html' with product_id=product.id %} 
  	  </td>
      <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
    <tr>
    	<td colspan="2"></td>
    	<td><b>Subtotal </b><span class='cart-subtotal'>{{ cart.subtotal }}</span></td>
    </tr>
    <tr>
    	<td colspan="2"></td>
    	<td><b>Total </b><span class='cart-total'>{{ cart.total }}</span></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><a class='btn btn-lg btn-success' href="{% url 'carts:checkout' %}">Checkout</a></td>
    </tr>         
  </tbody>
</table>
<div class='cart-remove-form' style='display: none;'>
  {% include 'carts/remove_form.html'%}
</div>
{% else %}
<p>Your cart is empty.</p>
{% endif %}
{% endblock content %}

templates/carts/remove_form.html
<form class='form-product-ajax' method='POST' action="{% url 'carts:update' %}" data-endpoint="{% url 'carts:update' %}" class="form">{% csrf_token %}
	<input class='cart-product-id' type="hidden" name="product_id" value='{{ product.id }}'>
	In cart<button type='submit' class='btn btn-link'>Remove?</button>


</form>